// <auto-generated />
using System;
using Checkpoint.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Checkpoint.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250905145633_CriacaoInicial")]
    partial class CriacaoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Checkpoint.Model.RM99500_Fornecedor", b =>
                {
                    b.Property<int>("idFornecedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idFornecedor"));

                    b.Property<string>("Cidade")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Estado")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("dsEndereco")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("nrCEP")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("idFornecedor");

                    b.ToTable("RM99500_Fornecedor", (string)null);
                });

            modelBuilder.Entity("Checkpoint.Model.RM99500_Pedido", b =>
                {
                    b.Property<int>("idPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPedido"));

                    b.Property<DateTime>("dataPedido")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<decimal>("valorTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("idPedido");

                    b.ToTable("RM99500_Pedido", (string)null);
                });

            modelBuilder.Entity("Checkpoint.Model.RM99500_Produto", b =>
                {
                    b.Property<int>("idProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idProduto"));

                    b.Property<string>("nmProduto")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("preco")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("idProduto");

                    b.ToTable("RM99500_Produto", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
